const GET_DATA_CONTACT_PAGE = `query($language:LanguageCodeEnum!){
  page(id:"cG9zdDo2OTU="){
   translation(language:$language){
     contact{
      banner{
        background{
          sourceUrl
          altText
        }
        title
        subTitle
      }
      contentAddress{
        heading
        listContentAddress{
          title
          subTitle
          icon{
            altText
            sourceUrl
          }
          infomation
        }
        image{
          sourceUrl
          altText
        }
      }
      contentContact{
        heading
        address{
          text
        }
        formData{
          title
          name
          email
          telephone
          content
          button
        }
      }
    }
  }
  }
}`

export {
    GET_DATA_CONTACT_PAGE
}