const GET_DATA_TECHNOLOGY_OFFSET = `query getDataPageOffset($language :LanguageCodeEnum!){
  page(id:"cG9zdDo1MzA="){
		translation(language:$language){
      slug
      technology_common{
      banner{
        background{
          sourceUrl
          altText
        }
        title
      }
      content{
        titlePage
        introduce{
          heading
          description
        }
        system{
          title
          description
          gallery{
            sourceUrl
            altText
          }
        }
        mainContent{
          heading
          description
          listContent{
            icon{
              sourceUrl
              altText
            }
            text
          }
          image{
            sourceUrl
            altText
          }
        }
      }
    }
    }
  }
}`

const GET_DATA_TECHNOLOGY_FLEXO = `query getDataPageFlexo($language :LanguageCodeEnum!){
  page(id:"cG9zdDo1MzI="){
		translation(language:$language){
      slug
      technology_common{
      banner{
        background{
          sourceUrl
          altText
        }
        title
      }
      content{
        titlePage
        introduce{
          heading
          description
        }
        system{
          title
          description
          gallery{
            sourceUrl
            altText
          }
        }
        mainContent{
          heading
          description
          listContent{
            icon{
              sourceUrl
              altText
            }
            text
          }
          image{
            sourceUrl
            altText
          }
        }
      }
    }
    }
  }
}`

const GET_DATA_TECHNOLOGY_GRAVURE = `
query getDataPageGravure($language :LanguageCodeEnum!){
  page(id:"cG9zdDo1MzY="){
		translation(language:$language){
      slug
      technology_common{
      banner{
        background{
          sourceUrl
          altText
        }
        title
      }
      content{
        titlePage
        introduce{
          heading
          description
        }
        system{
          title
          description
          gallery{
            sourceUrl
            altText
          }
        }
        mainContent{
          heading
          description
          listContent{
            icon{
              sourceUrl
              altText
            }
            text
          }
          image{
            sourceUrl
            altText
          }
        }
      }
    }
    }
  }
}`

const GET_DATA_TECHNOLOGY_DIGITAL = `
query getDataPageDigital($language :LanguageCodeEnum!){
  page(id:"cG9zdDo1NDI="){
		translation(language:$language){
      slug
      technology_common{
      banner{
        background{
          sourceUrl
          altText
        }
        title
      }
      content{
        titlePage
        introduce{
          heading
          description
        }
        system{
          title
          description
          gallery{
            sourceUrl
            altText
          }
        }
        mainContent{
          heading
          description
          listContent{
            icon{
              sourceUrl
              altText
            }
            text
          }
          image{
            sourceUrl
            altText
          }
        }
      }
    }
    }
  }
}`

const GET_DATA_TECHNOLOGY_OTHERPRINT = `query getDataPageOtherPrint($language :LanguageCodeEnum!){
  page(id:"cG9zdDo1NDQ="){
		translation(language:$language){
      slug
      technology_otherPrinting{
        banner{
          background{
            sourceUrl
            altText
          }
          title
        }
        content{
          titlepage
          introduce{
            heading
            description
          }
          solutions{
            title
            listSolution{
              solution
            }
          }
          mainContent{
            heading
            description
            listContent{
              icon{
                sourceUrl
                altText
              }
            }
            subContent
          }
        }
      }
    }
  }
}`

export {
  GET_DATA_TECHNOLOGY_DIGITAL,
  GET_DATA_TECHNOLOGY_GRAVURE,
  GET_DATA_TECHNOLOGY_OTHERPRINT,
  GET_DATA_TECHNOLOGY_OFFSET,
  GET_DATA_TECHNOLOGY_FLEXO
}